dist: trusty
sudo: required

language: node_js
node_js:
  - "6.9"
  - "4.6"
cache:
  directories: node_modules
branches:
  only: master

addons:
  firefox: "latest"
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - if [[ `npm -v` != 4* ]]; then npm i -g npm@4; fi

before_script:
  - export CHROME_BIN=$(which google-chrome)
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script: npm run test:ci

after_script: npm run test:ci:coveralls